services:
  notes-db:
    container_name: notes-db
    image: postgres:17
    # image: timescale/timescaledb:latest-pg16
    ports:
      - 5000:5432
    env_file: ./envs/superuser.env
    volumes:
      - ./_dockerdata/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - notes

networks:
  notes:
    external: true
